name: spotify_clone
description: "A replica of the Spotify app built with Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  #UI
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

  #State management
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  equatable: ^2.0.5
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.2
  pine: ^1.0.3

  #Navigation
  go_router: ^14.3.0

  #Utils
  json_annotation: ^4.8.1
  copy_with_extension: ^6.0.0
  collection: ^1.18.0
  logger: ^2.4.0
  form_validator: ^2.1.1

  #Firebase
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3

  #Sign in
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3

  #Audio
  just_audio: ^0.9.42
  audio_session: ^0.1.23
  just_audio_background: ^0.0.1-beta.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1
  copy_with_extension_gen: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/

flutter_native_splash:
  color: "#000000"
  image: assets/images/spotify_logo.png
  android: true
  ios: true
  web: false

  android_gravity: centerInside
  ios_content_mode: scaleAspectFit

  android_12:
    image: assets/images/spotify_logo.png
    color: "#000000"


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/spotify_icon_logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/spotify_icon_logo.png"
    background_color: "#000000"
    theme_color: "#000000"